### ISSUE TITLE
review assets building process

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-cli#142]
The Dockerfile has a flag to build assets or not, this is because the invenio-cli containerize does so and therefore there was a need to duplicate said part of the process. Why? Docker image caching?

Maybe the assets re-built should be done by invenio-cli update.

**Comment by fenekku** [comment]
To put some context here:

There is actually 2 scenarios that the Dockerfile generated image is trying to satisfy:

1- local development / local containerized (under this model they fall in the same scenario)
2- kubernetes deployment

So far, we have taken the approach that the docker image *can be made* to contain assets for case 2- via `$include_assets`. The idea (maybe it was a restriction of kubernetes) being that we ship a completely packaged image to kubernetes and it just manipulates it. This image contains static assets in it. 

The deployment image is "completely-packaged". On the other hand, the local containerized/development one is not quite: it uses docker volumes to hold data and in particular static assets. We do this so that the nginx container has access to assets that it didn't build / aren't in its container. If this explanation holds and I know nothing about kubernetes, I would suspect kubernetes is serving static assets via the uwsgi server rather than the nginx one or it does some magic to extract the assets into someplace where they can be served by nginx.

Ideally we want an equivalent of docker volume in kubernetes and I believe there are issues about that (sort-of).

**Comment by ppanero** [comment]
What you explain is correct. As clarification on Kubernetes, just specify that it is serving statics through Nginx, therefore option b (*t does some magic to extract the assets into someplace where they can be served by nginx.*) applies.

Might not be for june. We might want to rethink the steps in the future of the CLI. I would like to find a way of avoid having the `$include_assets`, but still we need a *fully packaged image* for cloud deployments.

We can shelve this one for upcoming months WDYT?

**Comment by ppanero** [comment]
Done in the new workflow: flag removed in the dockerfile, using docker cache.
