### ISSUE TITLE
Disable failure on deprecation warnings

### ISSUE THREAD

**Issue by cenouralm** [inveniosoftware/invenio-cli#147]
The error showed up when running `./run-tests.sh`: `ERROR  - pytest.PytestDeprecationWarning: Direct construction of Pep8Item has been deprecated, please use Pep8Item.from_parent.`
Uninstalled Pytest 6+ version and installed 5.4.3 version. After that installed 6+ version and added the line in the #146.

**Comment by ppanero** [comment]
The issue has to do with the fact that pytest 6+ is making deprecation warnings as a failure, instead of a warning. We need to come up with a strategy to address that on Invenio:

- Add the ignore deprecations to pytest.ini's all around
- Avoid having deprecation warnings. How to deal with that when is a 3rd party lib?

**Comment by zzacharo** [comment]
See also https://github.com/inveniosoftware/pytest-invenio/issues/54
