### ISSUE TITLE
docker-compose reaches EOL in June 

### ISSUE THREAD

**Issue by wgresshoff** [inveniosoftware/invenio-cli#348]
## Is your feature request related to a problem? Please describe.
docker-compose v1 reaches EOL end of june 2023. Additionally the syntax changes: instead of `docker-compose` new versions add `compose` as subcommand to docker, so it is `docker compose` instead.

## Describe the solution you'd like
Support `docker-compose` if available and the newe syntax `docker compose`.

## Describe alternatives you've considered
...

## Additional context
Official announcement: https://docs.docker.com/compose/reference/

**Comment by mfenner** [comment]
I have been using docker compose V2 and the new syntax `docker compose up` for some time now and have not encountered any problems. Example at https://github.com/front-matter/docker-invenio-rdm

**Comment by mfenner** [comment]
@karkraeg I used invenio-cli to build the docker images used in my Docker Compose setup.

**Comment by karkraeg** [comment]
@fenekku @ppanero I modified my Fork to use `docker compose` instead of `docker-compose` v1: https://github.com/inveniosoftware/invenio-cli/commit/8d77c22dd207ad385e50df29a44e8327526b0336

Would this change be of interest as a Pull Request?

`docker-compose`'s last release was more than two years ago: https://docs.docker.com/compose/migrate/#will-i-still-be-able-to-use-compose-v1-if-i-really-want-to

This would alter the installation dependencies for invenioRDM.

**Comment by fenekku** [comment]
@karkraeg Yes that would be great! You can make a PR on this repo and associate it with the "PR Community" project (I will be on the lookout for it anyway if there are logistical issues). 

What I am thinking is that we could either have a transition period where both are supported  (recent versions of docker install a `docker-compose` pass-through anyway) or make a clean break especially for upcoming v12. 

Clean break is probably easier and installing most recent version of docker is possible in any OS (we were initially a holdout because we didn't think our setup could support it, but it can!).

**Comment by mfenner** [comment]
Any updates on this?

**Comment by karkraeg** [comment]
> Any updates on this?

Hi, I'm currently on vacation, I will look into whats missing to merge the PR on the 24th of July or perhaps next week, but can't promise

**Comment by mfenner** [comment]
Thanks for the update. Docker-compose V1 has reached EOL in June, so there is some urgency to resolve this.
